use store;

INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('andres','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',1, 'andres', 'farfan','profesor@mail.com');
INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('admin','$2a$10$RmdEsvEfhI7Rcm9f/uZXPebZVCcPC7ZXZwV51efAvMAp1rIaRAfPK',1, 'John', 'Doe','jhon.doe@mail.com');

INSERT INTO `roles` (nombre) VALUES ('ROLE_USER');
INSERT INTO `roles` (nombre) VALUES ('ROLE_ADMIN');

INSERT INTO `usuarios_roles` (usuario_id, role_id) VALUES (1, 1);
INSERT INTO `usuarios_roles` (usuario_id, role_id) VALUES (2, 2);
INSERT INTO `usuarios_roles` (usuario_id, role_id) VALUES (2, 1);

INSERT INTO CLIENTE (NOMBRE, APELLIDO, DNI,TELEFONO,EMAIL) VALUES ('Juan','Gonzales',33774488,987543281, 'juan.gonzales@gmail.com');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, DNI,TELEFONO,EMAIL) VALUES ('Erick','Alfaro',8866338,987543281, 'erick.alfaro@gmail.com');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, DNI,TELEFONO,EMAIL) VALUES ('Karina','Hilario',33774499,983576281, 'k.hilario@gmail.com');

INSERT INTO VENTA(IDCLIENTE,FECHA) VALUES(1,STR_TO_DATE('21-07-2020','%d-%m-%Y'));
INSERT INTO VENTA(IDCLIENTE,FECHA) VALUES(2,STR_TO_DATE('12-06-2020','%d-%m-%Y'));
INSERT INTO VENTA(IDCLIENTE,FECHA) VALUES(3,STR_TO_DATE('20-02-2020','%d-%m-%Y'));
INSERT INTO VENTA(IDCLIENTE,FECHA) VALUES(2,STR_TO_DATE('11-11-2020','%d-%m-%Y'));

INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('mantequilla',1.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('leche',2.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('azucar',3.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('limon',2.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('tomate',1.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('papa',3.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('lechuga',1.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('yogurt',8.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('arroz',5.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('pan',1.0);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('mermelada',1.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('manjar',2.3);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('carne de res',7.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('pollo',9.5);
INSERT INTO PRODUCTO(NOMBRE,PRECIO) VALUES('carne molida',6.5);

INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(1,2);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(1,3);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(2,4);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(2,5);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(3,6);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(3,7);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(3,8);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(4,9);
INSERT INTO DETALLEVENTA(IDVENTA,IDPRODUCTO) VALUES(4,10);
