INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('andres','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',1, 'eduardo', 'pillco','profesor@mail.com');
INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('admin','$2a$10$RmdEsvEfhI7Rcm9f/uZXPebZVCcPC7ZXZwV51efAvMAp1rIaRAfPK',1, 'John', 'Doe','jhon.doe@mail.com');

INSERT INTO `roles` (nombre) VALUES ('ROLE_USER');
INSERT INTO `roles` (nombre) VALUES ('ROLE_ADMIN');

INSERT INTO `usuarios_roles` (usuarioid, roleid) VALUES (1, 1);
INSERT INTO `usuarios_roles` (usuarioid, roleid) VALUES (2, 2);
INSERT INTO `usuarios_roles` (usuarioid, roleid) VALUES (2, 1);

INSERT INTO CLIENTE (NOMBRE, APELLIDO, DNI,TELEFONO,EMAIL) VALUES ('Sara','Lopez',33774488,987543281, 'slopez@gmail.com');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, DNI,TELEFONO,EMAIL) VALUES ('Eduardo','Ramirez',8866338,987543281, 'edu.ramirez@gmail.com');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, DNI,TELEFONO,EMAIL) VALUES ('Giuliana','Pinedo',33774499,983576281, 'giu.pinedo@gmail.com');

INSERT INTO VENTA(CLIENTEID,FECHA) VALUES(1,STR_TO_DATE('21-07-2020','%d-%m-%Y'));
INSERT INTO VENTA(CLIENTEID,FECHA) VALUES(2,STR_TO_DATE('12-06-2020','%d-%m-%Y'));
INSERT INTO VENTA(CLIENTEID,FECHA) VALUES(3,STR_TO_DATE('20-02-2020','%d-%m-%Y'));
INSERT INTO VENTA(CLIENTEID,FECHA) VALUES(2,STR_TO_DATE('11-11-2020','%d-%m-%Y'));

INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('MAN','mantequilla',1.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('LEC','leche',2.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('AZ','azucar',3.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('LIM','limon',2.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('TOM','tomate',1.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('PAP','papa',3.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('LEC','lechuga',1.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('YOG','yogurt',8.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('ARR','arroz',5.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('PAN','pan',1.0);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('MEM','mermelada',1.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('MAJ','manjar',2.3);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('CAR','carne de res',7.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('POL','pollo',9.5);
INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBRE,PRECIO) VALUES('CMO','carne molida',6.5);

INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(1,2);
INSERT INTO DETALLEVENTA(VENTAID,IDPRODUCTO) VALUES(1,3);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(2,4);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(2,5);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(3,6);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(3,7);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(3,8);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(4,9);
INSERT INTO DETALLEVENTA(VENTAID,PRODUCTOID) VALUES(4,10);