name: ShoppingCart Workflow
on:
  push:
    branches:
      - "main"

env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "corretto"
  MAVEN_VERSION: "3.9.8"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set upt JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.JAVA_DISTRIBUTION}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          maven-version: ${{env.MAVEN_VERSION}}

      - name: Build app
        run: mvn clean package

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true


